### PR TITLE
fix: stabilize config planning

### LINKED ISSUE #29: Fix inconsistent result for typed attributes and deprecated config with zero-value fields
## User Request

After deploying the gateway zero-value fix (gateway#66), new "inconsistent result after apply" failures surfaced for typed attributes and deprecated config paths. The gateway now faithfully returns all proto3 fields including zero values (`debounceMs: 0`, `restrictOutput: false`, etc.), but the provider isn't equipped to handle these server-defaulted fields.

### Root Cause

Proto3 without `optional` keywords always returns zero-value scalars. The gateway fix (PR #66) removed zero-value stripping, so the API now returns all fields. The provider's `apply*ConfigToModel()` functions set typed attributes from the API response, turning `null` plan values into `0`/`false`, which Terraform rejects as "inconsistent result."

#### Part A: Mark typed config attributes as `Optional + Computed` with `UseStateForUnknown`

Add `Computed: true` and the appropriate `UseStateForUnknown` plan modifier to all typed config attributes (not `id`, `title`, `description`, or `config`) in:

- `internal/resources/agent_resource.go` — `name`, `role`, `model`, `system_prompt`, `debounce_ms`, `when_busy`, `process_buffer`, `send_final_response_to_thread`, `restrict_output`, `restriction_message`, `restriction_max_injections`, `summarization_keep_tokens`, `summarization_max_tokens`
- `internal/resources/mcp_server_resource.go` — `namespace`, `command`, `workdir`, `request_timeout_ms`, `startup_timeout_ms`, `heartbeat_interval_ms`, `stale_timeout_ms`, nested `restart` block + inner attrs
- `internal/resources/workspace_configuration_resource.go` — `image`, `initial_script`, `cpu_limit`, `memory_limit`, `platform`, `enable_dind`, `ttl_seconds`, nested `volumes` block + inner attrs, `nix`
- `internal/resources/memory_bucket_resource.go` — `scope`, `collection_prefix`

This tells Terraform "the provider may fill in a value the user didn't set," making `unknown → 0` transitions valid.

#### Part B: Key-projection in `configStateValue()` for deprecated config path

In `internal/resources/json_helpers.go`, when the full semantic comparison fails, project the API response down to only the keys present in the user's original JSON and compare again. If the projected version matches, preserve the user's original string.

Add a `projectJSONKeys(reference, source string) (string, error)` helper that extracts only user-specified keys from the response.

### Failing Tests (7)

| Test | Cause |
|------|-------|
| `TestAccAgynAgent_basic` | Part A: zero-value typed attrs |
| `TestAccAgynAgent_update` | Part A |
| `TestAccAgynAgent_import` | Part A |
| `TestAccAgynAgent_deprecatedConfig` | Part B: extra zero-value keys in config JSON |
| `TestAccAgynMCPServer_basic` | Part A |
| `TestAccAgynMCPServer_deprecatedConfig` | Part B |
| `TestAccAgynAttachment_mcpServerWorkspaceConfiguration` | Part B (compound) |

### New Unit Tests

- `TestProjectJSONKeys` — key projection logic
- `TestConfigStateValueWithExtraZeroKeys` — `configStateValue` preserves user JSON when response has extra zero-value keys

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- mark typed config attributes as optional+computed with state retention
- add config JSON key projection to reduce plan drift
- expand JSON helper unit tests for projection and semantic compare

## Testing
- go build ./...
- go vet ./...
- go test ./...

Fixes #29

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Summary
- mark typed config attributes as optional+computed with state retention
- add config JSON key projection to reduce plan drift
- expand JSON helper unit tests for projection and semantic compare

## Test & Lint Summary
- go build ./...
- go vet ./...
- go test ./...

Tests: passed 3, failed 0, skipped 0
Lint: no issues

File: internal/resources/mcp_server_resource.go [hunk 1]
```diff
@@ -97,43 +98,62 @@ func (r *mcpServerResource) Schema(_ context.Context, _ resource.SchemaRequest,
...
 				Optional:            true,
+				Computed:            true,
 				MarkdownDescription: "Stale timeout in milliseconds.",
+				PlanModifiers:       []planmodifier.Int64{int64planmodifier.UseStateForUnknown()},
 			},
 			"restart": schema.SingleNestedAttribute{
 				Optional:            true,
+				Computed:            true,
 				MarkdownDescription: "Restart policy configuration.",
 				Attributes: map[string]schema.Attribute{
```
Comment (noa-lucent) [inline internal/resources/mcp_server_resource.go]: [major] The `restart` `SingleNestedAttribute` is marked `Optional + Computed` but is missing `objectplanmodifier.UseStateForUnknown()` on the parent block's `PlanModifiers`. The child attribute plan modifiers only take effect when the parent block is already non-null in the plan. If a user omits the `restart` block entirely, the plan will have it as null, and the provider populating it from the API response will cause "inconsistent result after apply."

Add:
```go
"restart": schema.SingleNestedAttribute{
    Optional:            true,
    Computed:            true,
    MarkdownDescription: "Restart policy configuration.",
    PlanModifiers:       []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
    Attributes: map[string]schema.Attribute{
        ...
    },
},
```

**Comment by casey-brooks** [comment]
## Summary
- add object-level UseStateForUnknown on restart and volumes blocks

## Test & Lint Summary
- go build ./...
- go vet ./...
- go test ./...

Tests: passed 3, failed 0, skipped 0
Lint: no issues

**Review by noa-lucent — APPROVED** [review]
Both fixes verified — `objectplanmodifier.UseStateForUnknown()` correctly added to the `restart` and `volumes` `SingleNestedAttribute` blocks with proper imports. All prior threads resolved.

LGTM.
