### PR TITLE
fix(resources): plan-aware config apply to fix inconsistent result errors

### LINKED ISSUE #29: Fix inconsistent result for typed attributes and deprecated config with zero-value fields
## User Request

After deploying the gateway zero-value fix (gateway#66), new "inconsistent result after apply" failures surfaced for typed attributes and deprecated config paths. The gateway now faithfully returns all proto3 fields including zero values (`debounceMs: 0`, `restrictOutput: false`, etc.), but the provider isn't equipped to handle these server-defaulted fields.

### Root Cause

Proto3 without `optional` keywords always returns zero-value scalars. The gateway fix (PR #66) removed zero-value stripping, so the API now returns all fields. The provider's `apply*ConfigToModel()` functions set typed attributes from the API response, turning `null` plan values into `0`/`false`, which Terraform rejects as "inconsistent result."

#### Part A: Mark typed config attributes as `Optional + Computed` with `UseStateForUnknown`

Add `Computed: true` and the appropriate `UseStateForUnknown` plan modifier to all typed config attributes (not `id`, `title`, `description`, or `config`) in:

- `internal/resources/agent_resource.go` — `name`, `role`, `model`, `system_prompt`, `debounce_ms`, `when_busy`, `process_buffer`, `send_final_response_to_thread`, `restrict_output`, `restriction_message`, `restriction_max_injections`, `summarization_keep_tokens`, `summarization_max_tokens`
- `internal/resources/mcp_server_resource.go` — `namespace`, `command`, `workdir`, `request_timeout_ms`, `startup_timeout_ms`, `heartbeat_interval_ms`, `stale_timeout_ms`, nested `restart` block + inner attrs
- `internal/resources/workspace_configuration_resource.go` — `image`, `initial_script`, `cpu_limit`, `memory_limit`, `platform`, `enable_dind`, `ttl_seconds`, nested `volumes` block + inner attrs, `nix`
- `internal/resources/memory_bucket_resource.go` — `scope`, `collection_prefix`

This tells Terraform "the provider may fill in a value the user didn't set," making `unknown → 0` transitions valid.

#### Part B: Key-projection in `configStateValue()` for deprecated config path

In `internal/resources/json_helpers.go`, when the full semantic comparison fails, project the API response down to only the keys present in the user's original JSON and compare again. If the projected version matches, preserve the user's original string.

Add a `projectJSONKeys(reference, source string) (string, error)` helper that extracts only user-specified keys from the response.

### Failing Tests (7)

| Test | Cause |
|------|-------|
| `TestAccAgynAgent_basic` | Part A: zero-value typed attrs |
| `TestAccAgynAgent_update` | Part A |
| `TestAccAgynAgent_import` | Part A |
| `TestAccAgynAgent_deprecatedConfig` | Part B: extra zero-value keys in config JSON |
| `TestAccAgynMCPServer_basic` | Part A |
| `TestAccAgynMCPServer_deprecatedConfig` | Part B |
| `TestAccAgynAttachment_mcpServerWorkspaceConfiguration` | Part B (compound) |

### New Unit Tests

- `TestProjectJSONKeys` — key projection logic
- `TestConfigStateValueWithExtraZeroKeys` — `configStateValue` preserves user JSON when response has extra zero-value keys

### PR DESCRIPTION
**Pull request by rowan-stein**
## Summary

Replaces the `Computed: true` + `UseStateForUnknown` strategy (from PR #30) with plan-aware `preserveOrApply*` helpers that only populate typed config attributes when the user explicitly set them in their Terraform config.

## Problem

PR #30's approach caused 3 categories of e2e failures:

1. **Nested struct pointer crash** — `restart` and `volumes` blocks (Go struct pointers) can't represent `unknown`, so `Computed + UseStateForUnknown` on the parent caused a crash when the user omitted the block.
2. **Typed attrs remain unknown on deprecated config path** — The guard `if configValue.IsNull() || configValue.IsUnknown()` skipped `apply*ConfigToModel()`, but `Computed` attrs start as `unknown` on first create with no prior state → Terraform rejects.
3. **API rejects zero-values on update** — `UseStateForUnknown` carried `0` from Create into Update plan → API rejected (e.g., `summarizationMaxTokens: 0` with minimum 1).

## Solution

- **Remove** `Computed: true` and `PlanModifiers` from all typed config attributes across all 4 resource schemas
- **Add `preserveOrApply*` helpers** (`preserveOrApplyString`, `preserveOrApplyInt64`, `preserveOrApplyBool`) in `common.go` — only populate a typed attr from the API response if the prior (plan/state) was non-null/non-unknown; otherwise return null
- **Add `preserveOrApplyRestart`** and **`preserveOrApplyVolumes`** for nested struct pointer blocks
- **Rename** existing unconditional `apply*ConfigToModel` → `apply*ConfigToModelFull` (used only by `UpgradeState`)
- **New plan-aware** `apply*ConfigToModel(model, config, prior)` using the preserve helpers
- **Update CRUD call sites** to capture `prior` before mutation and pass it
- **Add unit tests** for all `preserveOrApply*` helpers

## Changes

| File | Changes |
|------|---------|
| `common.go` | Add `preserveOrApplyString/Int64/Bool` helpers |
| `common_test.go` | Unit tests for preserve helpers |
| `agent_resource.go` | Schema cleanup, rename + new plan-aware apply |
| `mcp_server_resource.go` | Schema cleanup, `preserveOrApplyRestart`, rename + plan-aware apply |
| `workspace_configuration_resource.go` | Schema cleanup, `preserveOrApplyVolumes`, rename + plan-aware apply |
| `memory_bucket_resource.go` | Schema cleanup, rename + plan-aware apply |

## Verification

- `go build ./...` ✅
- `go vet ./...` ✅
- `go test ./...` ✅ (all unit tests pass)
- E2e acceptance tests: pending (requires local cluster)

Closes #29

### CODE REVIEW

File: internal/resources/workspace_configuration_resource.go [hunk 1]
```diff
@@ -570,6 +548,50 @@ func applyWorkspaceConfigToModel(model *workspaceConfigurationModel, config team
...
+		MountPath: preserveOrApplyString(prior.MountPath, apiVolumes.MountPath),
+	}
+}
+
+func applyWorkspaceConfigToModel(model *workspaceConfigurationModel, config teamapi.WorkspaceConfigurationConfig, prior workspaceConfigurationModel) diag.Diagnostics {
+	var diags diag.Diagnostics
+	model.Image = preserveOrApplyString(prior.Image, config.Image)
+	model.Env = envVarModelsFromAPI(config.Env)
+	model.InitialScript = preserveOrApplyString(prior.InitialScript, config.InitialScript)
+	if !prior.CpuLimit.IsNull() && !prior.CpuLimit.IsUnknown() {
```
Comment (noa-lucent) [inline internal/resources/workspace_configuration_resource.go]: [minor] The inline `if !prior.CpuLimit.IsNull() && !prior.CpuLimit.IsUnknown()` / `if !prior.MemoryLimit.IsNull()...` / `if !prior.Nix.IsNull()...` blocks repeat the same preserve-or-fallback pattern that the `preserveOrApply*` helpers encapsulate for other types.

Consider extracting small helpers (e.g., `preserveOrApplyRawMessage` and `preserveOrApplyNormalized`) to keep `applyWorkspaceConfigToModel` uniform and avoid the pattern divergence. This also reduces the chance of future copy-paste errors if more `json.RawMessage` or `jsontypes.Normalized` fields are added.
